name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2 # Choose a compatible Ruby version

      - name: Install Gems
        run: |
          gem install bundler jekyll

      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/github-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-jekyll-redirect